Repository firstcontributions/first-contributions, pull requests merged in 2018-08, with the labels that each got.

#5141 Add micheleb to Contributors list
  Contributors.md
Labels: updates needed :warning:

#5892 Added swedish translation and Johan Eriksson to Contributors list
  Contributors.md
  translations/README.se.md
Labels: :woman_technologist: waiting for review

#5902 added temp files, eslint, & spec files for Vim & sublime to .gitignore
  .gitignore
  Contributors.md
Labels: updates needed :warning:

#5934 Added a link to the swedish translation.
  README.md
  Translations.md
  translations/README.se.md
Labels: updates needed :warning:

#5947 Add Manish Kumar Jagnani To Contributors list and Added the 5 organistaions to the project
  Contributors.md
  app/package-lock.json
  app/src/components/ProjectList/listOfProjects.js
Labels: :woman_technologist: waiting for review

#5927 Feature/adding hebrew translation
  README.md
  Translations.md
  translations/README.hb.md
Labels: help wanted

#5931 Translate additional-material/additional-material.md and additional-m…
  additional-material/translations/additional-material.ru.md
  additional-material/translations/amending-a-commit.ru.md
Labels: :woman_technologist: waiting for review, help wanted

#6180 Amending a commit.urdu
  additional-material/git_workflow_scenarios/amending-a-commit.md
  additional-material/translations/amending-a-commit.ur.md
Labels: :woman_technologist: waiting for review
