Repository firstcontributions/first-contributions, pull requests merged in 2020-11, with the labels that each got.

#32483 Sindhi language
  Contributors.md
  translations/README.sindhi.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#32352 Add french translation of amending-a-commit.md
  additional-material/translations/amending-a-commit.fr.md
Labels: :woman_technologist: waiting for review, documentation

#33536 Add Italian translation for git-workflow/removing-a-file
  Contributors.md
  additional-material/translations/removing-a-file.it.md
Labels: documentation, hacktoberfest-accepted
