Repository firstcontributions/first-contributions, pull requests merged in 2020-10, with the labels that each got.

#30662 Translation of the IntelliJ tutorial and its inclusion on the home screen
  gui-tool-tutorials/translations/github-windows-intellij-tutorial.pt_br.md
  translations/README.pt_br.md
Labels: :woman_technologist: waiting for review, documentation

#31716 Update README.my.md
  translations/README.my.md
Labels: documentation

#32013 Some fixes in the ukrainian readme file
  translations/README.ua.md
Labels: documentation

#31740 Fix broken link on README.id.md part "Tutorial Menggunakan Alat Lain"
  translations/README.id.md
Labels: documentation, updates needed :warning:

#31828 Adding pt_br translation to github-desktop-tutorial.md
  gui-tool-tutorials/github-desktop-tutorial-ptBR.md
Labels: :woman_technologist: waiting for review, documentation, hacktoberfest-accepted

#31594 Guidelines for commit
  Contributors.md
  Guidelines for Commit.md
Labels: documentation, updates needed :warning:

#32726 Update README.guj.md
  translations/README.guj.md
Labels: :woman_technologist: waiting for review, documentation, hacktoberfest-accepted
