Repository firstcontributions/first-contributions, pull requests merged in 2022-10, with the labels that each got.

#57037 [Hungarian translation ] update content and correct typos
  translations/README.hu.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#57503 Grammatical errors and enhanced the sentences
  Contributors.md
  translations/README.hi.md
Labels: :woman_technologist: waiting for review

#59588 Add reviewers for Portuguese. Both Brazilian and Portugal
  .github/CONTRIBUTING.md
Labels: hacktoberfest-accepted

#59587 Update reviewers of Tamil and Serbian
  .github/CONTRIBUTING.md
Labels: hacktoberfest-accepted

#59583 Update code of conduct to version 2.1
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted
