Repository firstcontributions/first-contributions, pull requests merged in 2022-11, with the labels that each got.

#57583 Update README.pt_br.md
  translations/README.pt_br.md
Labels: hacktoberfest-accepted

#58540 Add git log file
  additional-material/git_workflow_scenarios/check-commit-log.md
Labels: hacktoberfest-accepted

#59152 Fixed typo
  translations/README.zh-cn.md
Labels: hacktoberfest-accepted

#59167 Adding quick ref for GIT workflow
  additional-material/git_workflow_scenarios/Useful-links-for-further-learning.md
Labels: hacktoberfest-accepted

#58507 add git workflow for `reset a branch` in the documentations
  additional-material/git_workflow_scenarios/resetting-a-branch.md
Labels: hacktoberfest-accepted

#58508 Update the Indonesian translation
  Contributors.md
  translations/README.id.md
Labels: hacktoberfest-accepted

#56918 Pashto/Afghanistan translation Added
  Contributors.md
  README.md
  translations/README.pus.md
Labels: hacktoberfest-accepted

#56590 Update README.cs.md
  translations/README.cs.md
Labels: hacktoberfest-accepted

#55981 Improved translations on translations/README.tl.md
  translations/README.tl.md
Labels: hacktoberfest-accepted

#58151 updates greek translation
  translations/README.gr.md
Labels: hacktoberfest-accepted

#55116 add Farsi(Persian) translation
  additional-material/translations/delete-branch-locally.fa.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#58581 Add tutorial for git bash
  cli-tool-tutorials/git-bash-windows-tutorial.md
Labels: hacktoberfest-accepted

#55430 Fixed the broken link of Kraken icon and intelliJ IDEA icon on README.al.md page
  Contributors.md
  translations/README.al.md
Labels: hacktoberfest-accepted

#57978 Update README.pl.md
  translations/README.pl.md
Labels: hacktoberfest-accepted

#57893 Update README.it.md
  translations/README.it.md
Labels: hacktoberfest-accepted

#58043 Fix some typing in Russian translation
  translations/README.ru.md
Labels: hacktoberfest-accepted

#59272 Fixed typos in MK translation
  translations/README.mk.md
Labels: hacktoberfest-accepted

#55668 Fix typos and make commands consistently hungarian
  translations/README.hu.md
Labels: hacktoberfest-accepted

#58001 Create Things a non Programmer can do
  Things a non Programmer can do
Labels: hacktoberfest-accepted

#56910 Changed git checkout command to git switch in hindi translation file
  Contributors.md
  translations/README.hi.md
Labels: hacktoberfest-accepted

#54915 add Yoruba translation of GitHub desktop
  Contributors.md
  gui-tool-tutorials/translations/github-desktop-tutorial.ng_yr.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#57330 docs: Fixed spelling and sentence mistakes in README.igb.md
  Contributors.md
  translations/README.igb.md
Labels: hacktoberfest-accepted

#59742 Improve pt-BR translation
  Contributors.md
  translations/README.pt_br.md
Labels: :woman_technologist: waiting for review

#57100 docs: Visual Studio 2017 PT-BR tutorial
  gui-tool-tutorials/translations/github-windows-intellij-tutorial.pt_br.md
  gui-tool-tutorials/translations/github-windows-vs2017-tutorial.pt_br.md
  translations/README.pt_br.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#59340 translating visual studio tutorial to pt_br
  gui-tool-tutorials/translations/github-windows-vs2017-tutorial.pt_br.md
Labels: hacktoberfest-accepted

#59493 GitKraken tutorial translated to PT-BR
  gui-tool-tutorials/translations/gitkraken-tutorial.pt-br.md
Labels: hacktoberfest-accepted

#58150 correcting indonesian grammar
  translations/README.id.md
Labels: hacktoberfest-accepted

#57220 Corrections in the translation to MX
  translations/README.mx.md
Labels: :woman_technologist: waiting for review, hacktoberfest-accepted

#56232 Added Richard Nikolas to Contributors list / Improved Portuguese (pt-br) translation
  Contributors.md
Labels: hacktoberfest-accepted

#59301 To 'tamilify' some sentencess
  translations/README.ta.md
Labels: hacktoberfest-accepted

#59262 docs: VS Code PT-BR tutorial
  gui-tool-tutorials/translations/github-windows-vs-code-tutorial_pt_br.md
Labels: hacktoberfest-accepted

#57207 New tutorial on how to make the first contribution with Github CLI
  github-cli-tutorial.md
Labels: hacktoberfest-accepted

#57781 Add Lao translation
  Contributors.md
  translations/README.la.md
  translations/Translations.md
Labels: hacktoberfest-accepted

#57722 fix Indonesian so hackers can understand
  translations/README.id.md
Labels: hacktoberfest-accepted

#58039 github-windows-vs-code-tutorial-hi.md
  gui-tool-tutorials/translations/github-windows-vs-code-tutorial-hi.md
Labels: hacktoberfest-accepted

#58239 Add Useful-links-for-further-learning in id translation
  additional-material/translations/Indonesian/additional-material.id.md
  additional-material/translations/Useful-links-for-further-learning.id.md
  gui-tool-tutorials/translations/github-windows-vs-code-tutorial_id.md
  translations/README.id.md
Labels: hacktoberfest-accepted

#59671 Paulpessoa translation vscode tutorial
  Contributors.md
  gui-tool-tutorials/translations/github-windows-vs-code-tutorial.pt_br.md
Labels: hacktoberfest-accepted

#58676 Add Marko to Contributors list and create croatian translation
  Contributors.md
Labels: hacktoberfest-accepted

#56829 feat: add amharic translation support
  Contributors.md
  README.md
  translations/README.am.md
Labels: hacktoberfest-accepted

#57367 Added slovak translation of readme, added myself to contributors, fix…
  Contributors.md
  translations/README.sk.md
  translations/Translations.md
Labels: hacktoberfest-accepted
